FROM node:24 AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY src/ ./src/
RUN npm run build

FROM node:24

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

EXPOSE 3003

ENV TARGET_SERVICE_URL="http://ts-target-service:3004"

CMD [ "node", "dist/index.js" ]
